### ISSUE TITLE
Rating for the task

### ISSUE THREAD

**Issue by avkhozov** [RYDLAB/jagc.org#10]
Do we need to allow the user to mark a task as +1 or -1 for the calculation of its rating? Thus tasks will cost a different amount of points. And it will not allow users collect a lot of points by creating simple tasks and solving them.

**Comment by vakorol** [comment]
Likes for tasks is a good idea. 

Although it should probably not directly affect the number of points issued for solving.

1. Maybe it's worth halving the amount points for tasks with negative rating -
so that solving a task with negative rating would bring 5 pts to the winner, 4 pts to solution #2, 3 pts to solution #3 etc, solutions after #5 would not get any points at all.

-Or-

2.  simply hide tasks with rating less than, say, -3.

**Comment by avkhozov** [comment]
Or may be we need only +1 (or likes). And may be we should give points only for tasks that have at least 5 likes.

**Comment by avkhozov** [comment]
Or we can don't use the likes, and give points only for tasks that are solved at least 5 people.

**Comment by vakorol** [comment]
"give points only for tasks that are solved at least 5 people" - this may be a bad idea, since there can be (and are already!) difficult tasks solved by only 2-3 people.
